shop/contact/urls.py
from django.urls import path

from contact import views


app_name = 'contact'
urlpatterns = [
    path('', views.emailView, name='contacts'),
    path('members/', views.MemberView.as_view(), name='members'),
]

shop/homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('mailing/', views.mailingView, name='mailing'),
]

shop/mainShop/urls.py
from django.urls import path

from mainShop import views


app_name = 'mainShop'
urlpatterns = [
    # path('', views.MenuView.as_view(), name='menu'),
    path('men/', views.MaleListView.as_view(), name='men'),
    path('women/', views.FemaleListView.as_view(), name='women'),
    path('return-policy/', views.ReturnAndExchangeView.as_view(), name='exchange'),

    path('<slug>', views.ModelFilteredListView.as_view(), name='detail'),
    path('<slug>/',
         views.shoes_detail_view,
         name='shoes'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('menu/', include('mainShop.urls')),
    path('contacts/', include('contact.urls')),
    path('order/', include('userOrder.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/templates/footer.html
{% load static %}

<!-- Footer -->
<footer class="page-footer font-small" style="font-family: sans-serif;">
  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row -->
    <div class="row justify-content-between">
      <!-- Grid column -->

      <div class="col-md-4">
        <!-- Content -->
        <ul class="list-group">
          <li class="list-group-item">Будни: <span class="float-right">10:00 - 20:00</span></li>
          <li class="list-group-item">Выходные: <span class="float-right">10:00 - 20:00</span></li>
          <li class="list-group-item">Тел.: <span class="float-right">0997436885 - Денис</span></li>
          <li class="list-group-item">Viber, Telegram: <span class="float-right ml-2">+380997436885</span></li>
          <li class="list-group-item">E-mail: <span class="float-right">kicksindustry@gmail.com</span></li>
        </ul>
      </div>
      <!-- Grid column -->

        <!-- Grid column -->
      <div class="col-md-3">
          <div class="container h-100" style="height: 40px; width: 150px;">
             <div class="row h-100 justify-content-center align-items-center py-3">
                <img src="{% static 'homepage/images/logo.png' %}" class="img img-fluid" alt="Kicks Industry Ужгород магазин обуви Nike, Adidas, Reebok, Saucony, New Balance, Asics, Puma, Native">
             </div>
         </div>
      </div>

      <!-- Grid column -->
      <div class="col-md-3">
          <!-- Links -->
          <ul class="list-group list-group-flush text-center">
            <li class="list-group-item"><a href="{% url 'homepage:index' %}">Главная</a></li>
            <li class="list-group-item"><a href="{% url 'mainShop:men' %}">Мужская обувь</a></li>
            <li class="list-group-item"><a href="{% url 'mainShop:women' %}">Женская обувь</a></li>
            <li class="list-group-item"><a href="{% url 'mainShop:exchange' %}">Возврат и обмен</a>
            <li class="list-group-item"><a href="{% url 'contact:contacts' %}">Обратная связь</a></li>
          </ul>
      </div>
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
      © {% now "Y" %} Copyright: <a href="{% url 'homepage:index' %}"> kicksindustry.com.ua </a>
  </div>
  <!-- Copyright -->

</footer>
  <!-- Footer -->

shop/templates/head.html
<head>
    {% load static %}

    {% include 'scripts.html' %}

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Kicks Industry - интернет-магазин обуви</title>
        <meta name="title" content="Kicks Industry - интернет-магазин обуви">
        <meta property=”og:title” content="Kicks Industry - интернет-магазин обуви"/>
    {% endif %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% if description %}
        <meta name="description" content="{{ description }}">
        <meta property=”og:description” content="{{ description }}" />
    {% else %}
        <meta name="description" content="Купить кроссовки Ужгород - лучшая цена - оригинальная обувь - доставка по Украине. В наличии: Adidas, Nike, New Balance, Reebok, Puma, Saucony, Native.">
    {% endif %}

    {% if keywords %}
        <meta name="keywords" content="{{ keywords }}">
    {% else %}
        <meta name="keywords" content="Adidas, Nike, Puma, New Balance, Reebok, Украина, купить кроссовки, купить обувь, Адидас, Найк, Рибок">
    {% endif %}

    <meta property=”og:type” content="Магазин"/>
    <meta property=”og:URL” content="https://kicksindustry.com.ua"/>
    <meta property=”og:image” content="{% static 'homepage/images/logo.png' %}"/>
    <meta property=”og:site_name” content="Kicks Industry" />

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/wrapper.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/welcome_text.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>

shop/templates/header.html
{% load static %}

<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-size: 17px; font-weight: bold;">
      <div class="container">
        <a class="navbar-brand ml-4" href="{% url 'homepage:index' %}">
          <img src="{% static 'homepage/images/logo.png' %}" alt="Kicks Industry Ужгород магазин обуви Nike, Adidas, Reebok, Saucony, New Balance, Asics, Puma, Native" style="height: 50px; width: 100px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive" style="font-family: sans-serif;">
          <ul class="nav nav-tabs justify-content-between ml-auto my-3 my-lg-0" role="tablist">
            <li class="nav-item">
                <a class="nav-link active text-success" href="{% url 'homepage:index' %}" role="tab" aria-selected="true">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'mainShop:men' %}" role="tab" aria-selected="false">Мужская обувь</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'mainShop:women' %}" role="tab" aria-selected="false">Женская обувь</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'mainShop:exchange' %}" role="tab" aria-selected="false">Возврат и обмен</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'contact:contacts' %}" role="tab" aria-selected="false">Обратная связь</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</header>

shop/templates/scripts.html
<!-- Google Tag Manager -->
<script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-KTNM2SV');
</script>
<!-- End Google Tag Manager -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<!-- Google Analytics -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-116385462-1', 'auto');
    ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
{#      AdSense script#}
<script data-ad-client="ca-pub-8196126504118351" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

shop/templates/structured_data.html
<!-- Разметка JSON-LD, созданная Мастером разметки структурированных данных Google. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Kicks Industry",
  "image" : "https://kicksindustry.com.ua/static/homepage/images/logo.png",
  "telephone" : "+380997436885",
  "email" : "kicksindustry@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "ул. Льва Толстого, 5, 1-ый этаж",
    "addressLocality" : "г. Ужгород",
    "addressCountry" : "Украина"
  },
  "openingHours":["Пн-Вс 10:00-20:00"],
  "url" : "https://kicksindustry.com.ua/"
}
</script>

shop/templates/wrapper.html
<!DOCTYPE html>
<html>
  {% include 'head.html' %}
  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KTNM2SV"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    {% include 'header.html' %}

    {% block carousele %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <hr>

    <div class="container text-center rounded" style="background: linear-gradient(90deg, rgba(53,94,0,1) 12%, rgba(38,175,0,0.8379726890756303) 43%, rgba(14,186,4,0.8323704481792717) 71%);">
        <a href="{% url 'homepage:mailing' %}"><button type="button" class="btn btn-light mt-2 mb-2 text-dark" style="font-size: 18px;">Подпишись на рассылку!</button></a>
    </div>

    <hr>

    {% include 'footer.html' %}
  </body>
</html>