shop/mainShop/urls.py
from django.urls import path

from mainShop import views


app_name = 'mainShop'
urlpatterns = [
    # path('', views.MenuView.as_view(), name='menu'),
    path('men/', views.MaleListView.as_view(), name='men'),
    path('women/', views.FemaleListView.as_view(), name='women'),
    path('return-policy/', views.ReturnAndExchangeView.as_view(), name='exchange'),

    path('<slug>', views.ModelFilteredListView.as_view(), name='detail'),
    path('<slug>/',
         views.shoes_detail_view,
         name='shoes'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('menu/', include('mainShop.urls')),
    path('contacts/', include('contact.urls')),
    path('order/', include('userOrder.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/userOrder/urls.py
from django.urls import path

from .views import UserOrderView, PayView, PayCallbackView


app_name = 'userOrder'
urlpatterns = [
    path('<int:id>/', UserOrderView, name='order'),
    path('pay/<price>', PayView.as_view(), name='pay_view'),
    path('pay-callback/', PayCallbackView.as_view(), name='pay_callback'),
]

shop/mainShop/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.urls import reverse
from autoslug import AutoSlugField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=64)
    sex = models.CharField(max_length=64, default='unisex')
    image = models.ImageField(default='', upload_to='category', validators=[
                              FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])
    size_table = models.ImageField(upload_to='size_table', validators=[
        FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])],
        default='noimage.jpg')
    # slug = models.SlugField(unique=True)
    slug = AutoSlugField(populate_from='name', unique=True)

    class Meta:
        verbose_name = '.Бренд'
        verbose_name_plural = '.Бренды'

    def __str__(self):
        return f'{self.name} {self.sex}'

    def get_absolute_url(self):
        return reverse('mainShop:detail', kwargs={'slug': self.slug})


class Shoes(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='shoes', validators=[
                              FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])],)
    articul = models.CharField(max_length=64, default='')
    model = models.CharField(max_length=128)
    price = models.FloatField(default='1.0')
    discount = models.BooleanField(default=False)
    price_after_discount = models.FloatField(default='0.0', blank=True)
    description = models.TextField(default='')
    is_active = models.BooleanField()
    quantity = models.PositiveIntegerField(default=0)
    sale_cnt = models.PositiveIntegerField(default=0)
    add_date = models.DateTimeField(verbose_name='added date', auto_now=True)
    # slug = models.SlugField(unique=True)
    slug = AutoSlugField(populate_from='model', unique=True)

    class Meta:
        verbose_name = '.Модель'
        verbose_name_plural = '.Модель'

    def __str__(self):
        return self.model

    def get_absolute_url(self):
        return reverse('mainShop:shoes', kwargs={'slug': self.slug})


""" Start of gallery """


class ShoesGallery(models.Model):
    shoes = models.OneToOneField(Shoes,
                                 on_delete=models.CASCADE,)

    class Meta:
        verbose_name = '.Галерея'
        verbose_name_plural = '.Галереи'

    def __str__(self):
        return f'Артикул: {self.shoes.articul}, пара: {self.shoes.category.name}  {self.shoes.model}'


class ShoesImage(models.Model):
    shoes_gallery = models.ForeignKey(ShoesGallery, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='shoes_detail', validators=[
                              FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])],
                              default='noimage.jpg')

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"

    def __str__(self):
        return f'Артикул: {self.shoes_gallery.shoes.articul}, пара:{self.shoes_gallery.shoes.category.name} {self.shoes_gallery.shoes.model}'


""" End of gallery """


""" Start of size-list"""


class ModelSizeList(models.Model):
    shoes = models.OneToOneField(Shoes,
                                 on_delete=models.CASCADE,)

    class Meta:
        verbose_name = '.Размеры'
        verbose_name_plural = '.Размеры'

    def __str__(self):
        return f'Артикул: {self.shoes.articul}, пара: {self.shoes.category.name}  {self.shoes.model}'


class ShoesSize(models.Model):
    shoes_size = models.ForeignKey(ModelSizeList, on_delete=models.CASCADE)
    model_size = models.CharField(max_length=10, default='')
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Размер"
        verbose_name_plural = "Размер"

    def __str__(self):
        return f'Артикул: {self.shoes_size.shoes.articul}, размер: {self.model_size}, пара: {self.shoes_size.shoes.category.name} {self.shoes_size.shoes.model}'


""" End of model size list """

shop/mainShop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django_filters.views import FilterView
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.db.models import Q

from .filters import ShoesFilter
from .models import *


class MaleListView(generic.ListView):
    model = Shoes
    template_name = 'mainShop/male.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['male_list'] = Category.objects.filter(sex='men').order_by("name")
        context['title'] = 'Мужские кроссовки - Kicks Industry'
        context['description'] = 'Мужские оригинальные кроссовки в интернет-магазине ➦Kicks Industry. ☎: (099) 743-68-85. Мужские кроссовки, $ лучшие цены, ✈ быстрая доставка, ☑ гарантия!' \
                                 '₴ Скидочные сертификаты'
        context['keywords'] = 'Купить кроссовки, купить мужскую обувь, дешево, Adidas, Nike, Reebok, ' \
                              'адидас, найк, рибок, Украина, Ужгород, Киев, Харьков, Одесса, Львов'
        return context


class FemaleListView(generic.ListView):
    model = Shoes
    template_name = 'mainShop/female.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['female_list'] = Category.objects.filter(sex='women').order_by("name")
        context['title'] = 'Женские кроссовки - Kicks Industry'
        context['description'] = 'Женские оригинальные кроссовки в интернет-магазине ➦Kicks Industry. ☎: (099) 743-68-85. Женские кроссовки, $ лучшие цены, ✈ быстрая доставка!' \
                             '₴ Скидочные сертификаты'
        context['keywords'] = 'Купить кроссовки, купить женскую обувь, дешево, Adidas, Nike, Reebok,' \
                              'адидас, найк, рибок, Украина, Ужгород, Киев, Харьков, Одесса, Львов'
        return context


class ReturnAndExchangeView(generic.TemplateView):
    template_name = 'mainShop/return_and_exchange.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = 'Возврат и обмен - Kicks Industry'
        context['description'] = 'Обмен и возврат на протяжении 14 дней в интернет-магазине ➦Kicks Industry. ☎: (099) 743-68-85.'
        context['keywords'] = 'Возврат кроссовок, обмен кроссовок, гарантия, Киев, Ужгород, Киев, Харьков, Одесса, Львов'
        return context

# start of menu detail view (example: nike (male) -> nike shoes)

class ModelFilteredListView(FilterView):
    filterset_class = ShoesFilter
    template_name = 'mainShop/detail.html'
    paginate_by = 24
    ordering = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        context['title'] = f"Кроссовки {category.name} - Kicks Industry"
        context['description'] = 'Мужские и женские оригинальные кроссовки в интернет-магазине ➦Kicks Industry. ☎: (099) 743-68-85. ' \
                                 'Мужские и женские кроссовки, $ лучшие цены, ✈ быстрая доставка!' \
                                 '₴ Скидочные сертификаты'
        context['keywords'] = 'Купить кроссовки, купить женскую обувь, купить мужскую обувь, дешево, Adidas, Nike, Reebok,' \
                              'адидас, найк, рибок, Украина, Ужгород, Киев, Харьков, Одесса, Львов'
        return context

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Shoes.objects.filter(category=category)


# end of menu detail view (example: nike (male) -> nike shoes)

def shoes_detail_view(request, slug):
    shoes = get_object_or_404(Shoes, slug=slug)
    images = ShoesImage.objects.filter(shoes_gallery__shoes=shoes)
    sizes = ShoesSize.objects.filter(shoes_size__shoes=shoes).exclude(is_active=False).order_by("model_size")
    size_table = shoes.category.size_table
    title = f'{shoes.category.name} {shoes.model} - Kicks Industry'
    description = f'{shoes.category.name} {shoes.model} - {shoes.price}₴. Размеры: {sizes}. Мужские и женские оригинальные кроссовки в интернет-магазине ➦Kicks Industry. ' \
                  '☎: (099) 743-68-85. ✈ быстрая доставка! ₴ Скидочные сертификаты'
    keywords = f'{shoes.category.name}, {shoes.model}, дешево, оригинал, Украина, Ужгород, Киев, Харьков, Одесса, Львов'
    return render(request, 'mainShop/shoes.html', {'shoes': shoes,
                                                   'images': images,
                                                   'sizes': sizes,
                                                   'size_table': size_table,
                                                   'description': description,
                                                   'keywords': keywords,
                                                   'title': title})

shop/templates/mainShop/female.html
{% extends "wrapper.html" %}

{% load static %}

{% block content %}

{% if female_list %}
    <div class="container justify-content-center">
        <div class="row" style="font-family: sans-serif;">
            {% for pos in female_list %}
                {% if pos.shoes_set.count > 0 %}
                    <div class="card mx-auto d-flex justify-content-center shadow-lg" style="margin-top: 25px; width: 16rem;">
                      <a href="{% url 'mainShop:detail' pos.slug %}">
                        <img class="card-img-top img-fluid rounded mx-auto d-block" src="{{ pos.image.url }}" alt="{{ pos.name }}" style="width: 240px; height: 180px;">
                      </a>
                      <div class="card-body">
                        {% if pos.sex == 'women' %}
                            <h1 class="card-title mb-3 mx-auto text-center" style="font-size: 17px;"><a class="text-dark" href="{% url 'mainShop:detail' pos.id %}"><strong>{{ pos.name }}</strong></a> <span class="badge badge-success" style="font-size: 14px;">{{ pos.shoes_set.count }}</span></h1>
                        {% endif %}
                        <div class="card-footer d-flex justify-content-center">
                            <a href="{% url 'mainShop:detail' pos.slug %}" class="btn btn-outline-dark">Перейти</a>
                        </div>
                      </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="container justify-content-center">
        <div class="row">
            <div class="card mx-auto">
                <div class="card-body mt-2 mb-2">
                    <h2 class="card-title">Нет результатов.</h2>
                    <p class="card-text">Тут пока пусто:(</p>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{#	<!--<br>-->#}
{#	<!--<div class="container d-flex justify-content-center" style="font-family: sans-serif;">-->#}
{#	<!--	  <ul class="pagination">-->#}
{##}
{#	<!--	    {% if page_obj.has_previous %}-->#}
{#	<!--	      <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">&laquo;</a></li>-->#}
{#	<!--	    {% else %}-->#}
{#	<!--	      <li class="disabled btn btn-primary"><span>&laquo;</span></li>-->#}
{#	<!--	    {% endif %}-->#}
{##}
{#	<!--	    {% for i in paginator.page_range %}-->#}
{#	<!--	      {% if page_obj.number == i %}-->#}
{#	<!--	        <li class="active"><span class="btn btn-success">{{ i }} <span class="sr-only">(current)</span></span></li>-->#}
{#	<!--	      {% else %}-->#}
{#	<!--	        <li><a href="?page={{ i }}" class="btn btn-primary">{{ i }}</a></li>-->#}
{#	<!--	      {% endif %}-->#}
{#	<!--	    {% endfor %}-->#}
{##}
{#	<!--	    {% if page_obj.has_next %}-->#}
{#	<!--	      <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">&raquo;</a></li>-->#}
{#	<!--	    {% else %}-->#}
{#	<!--	      <li class="disabled btn btn-primary"><span>&raquo;</span></li>-->#}
{#	<!--	    {% endif %}-->#}
{#	<!--	  </ul>-->#}
{#	<!--</div>-->#}

{% endblock %}

shop/templates/mainShop/menu.html
{% extends "wrapper.html" %}

{% load static %}

{% block content %}

	<div class="row" style="font-family: sans-serif;">
		{% for pos in menu_list %}
			<div class="card mx-auto d-flex justify-content-center shadow-lg" style="margin-top: 25px;">
			  <a href="{% url 'mainShop:detail' pos.slug %}">
			  	<img class="card-img-top img-fluid rounded mx-auto d-block" src="{{ pos.image.url }}" alt="{{ pos.name }}" style="width: 240px; height: 180px;">
			  </a>
			  <div class="card-body">
			    {% if pos.sex == 'men' %}
		  		    <h5 class="card-title mb-3 mx-auto text-center"><a class="text-dark" href="{% url 'mainShop:detail' pos.id %}" style="font-size: 18px;">Мужские кроссовки {{ pos.name }}</a> <span class="badge badge-success">{{ pos.shoes_set.count }}</span></h5>
		  	    {% else %}
		  		    <h5 class="card-title mb-3 mx-auto text-center"><a class="text-dark" href="{% url 'mainShop:detail' pos.id %}" style="font-size: 18px;">Женские кроссовки {{ pos.name }}</a> <span class="badge badge-success">{{ pos.shoes_set.count }}</span></h5>
		  	    {% endif %}
			    <div class="card-footer d-flex justify-content-center">
				    <a href="{% url 'mainShop:detail' pos.slug %}" class="btn btn-primary bg-info text-white">Перейти</a>
			    </div>
			  </div>
			</div>
		{% endfor %}
	</div>

	<br>
	<div class="container d-flex justify-content-center" style="font-family: sans-serif;">
		  <ul class="pagination">

		    {% if page_obj.has_previous %}
		      <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">&laquo;</a></li>
		    {% else %}
		      <li class="disabled btn btn-primary"><span>&laquo;</span></li>
		    {% endif %}

		    {% for i in paginator.page_range %}
		      {% if page_obj.number == i %}
		        <li class="active"><span class="btn btn-success">{{ i }} <span class="sr-only">(current)</span></span></li>
		      {% else %}
		        <li><a href="?page={{ i }}" class="btn btn-primary">{{ i }}</a></li>
		      {% endif %}
		    {% endfor %}

		    {% if page_obj.has_next %}
		      <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">&raquo;</a></li>
		    {% else %}
		      <li class="disabled btn btn-primary"><span>&raquo;</span></li>
		    {% endif %}
		  </ul>
	</div>

{% endblock %}

shop/templates/mainShop/shoes.html
{% extends "wrapper.html" %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static "mainShop/css/shoes.css" %}">


{% block content %}
    <!-- Разметка JSON-LD, созданная Мастером разметки структурированных данных Google. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Product",
      "name" : "{{ shoes.model }}",
      "image" : "{{ shoes.image.url }}",
      "description" : "{{ shoes.description }}",
      "sku" : "{{ shoes.articul }}",
      "brand" : {
        "@type" : "Brand",
        "name" : "{{ shoes.category.name }}"
      },
      "offers" : {
        "@type" : "Offer",
        "price" : "{{ shoes.price }}",
        "availability" : "http://schema.org/InStock",
        "priceCurrency" : "UAH",
        "url" : "{{ shoes.get_absolute_url }}"
      }
    }
    </script>

{#    <div class="container">#}
{#        <nav aria-label="breadcrumb">#}
{#          <ol class="breadcrumb">#}
{#            <li class="breadcrumb-item active" aria-current="page">{{ shoes.get_absolute_url }}</li>#}
{#          </ol>#}
{#        </nav>#}
{#    </div>#}

	<div class="card shadow-lg" style="margin-top: 10px; font-family: sans-serif;">
		<div class="container">
			<div class="row justify-content-md-center">
			    {% for img in images %}
			  	    <div class="col col-md-2">
                        
						<a data-toggle="modal" data-target="#image{{ forloop.counter }}">
						  	<img class="img-fluid card-img-top rounded mx-auto d-block img-circle zoom" src="{{ img.image.url }}" alt="{{ shoes.category.name }} {{ shoes.model }}" style="margin-top: 10px;">
						</a>

						<!-- Modal -->
						<div class="modal fade" id="image{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						  <div class="modal-dialog modal-lg" role="document">
						    <div class="modal-content">
						      <div class="modal-body">

    					      	<button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
					                <span aria-hidden="true">&times;</span>
					            </button>
					      	    <p style="text-align: center;" id="exampleModalLongTitle">{{ shoes.category.name }} {{ shoes.model }}</p>

						        <img class="img-fluid card-img-top rounded d-block" src="{{ img.image.url }}" alt="{{ shoes.category.name }} {{ shoes.model }}">
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
						      </div>
						    </div>
						  </div>
						</div>
						<!-- End modal -->
					</div>
		    	{% endfor %}

				<div class="container d-flex justify-content-center">
					<a class="btn btn-link" data-toggle="modal" data-target="#core-image-zoom">
					  	<img class="img-fluid card-img-top rounded mx-auto d-block img-circle zoom border border-left-0 border-right-0" src="{{ shoes.image.url }}" alt="{{ shoes.category.name }} {{ shoes.model }} {% for item in shoes.modelsizelist.shoessize_set.all %} {{ item.model_size }} {% endfor %}" style="width: 400px; margin-top: 10px;">
					</a>

					<!-- Modal -->
					<div class="modal fade" id="core-image-zoom" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
					  <div class="modal-dialog modal-lg" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <p class="modal-title" id="exampleModalLongTitle">{{ shoes.category.name }} {{ shoes.model }}</p>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        <img class="img-fluid card-img-top rounded d-block" src="{{ shoes.image.url }}" alt="{{ shoes.category.name }} {{ shoes.model }}">
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
					      </div>
					    </div>
					  </div>
					</div>
					<!-- End modal -->
				</div>
			</div>
		</div>

	  <div class="card-body text-center mx-auto">
		<h1 class="card-title text-dark" style="font-size: 20px;">{{ shoes.category.name }} {{ shoes.model }}</h1>
		<h2 class="card-title text-dark" style="font-size: 17px;">Артикул: {{ shoes.articul }}</h2>

		<p class="card-text">
            {% if shoes.is_active == True %}
                <div class="d-flex justify-content-center">
                    <p style="margin-top: 10px;"><span class="alert alert-success text-dark"><b>В наличии</b></span></p>
                </div>
            {% else %}
                <div class="d-flex justify-content-center">
                    <p style="margin-top: 10px;"><span class="alert alert-danger text-dark"><b>Нет в наличии</b></span></p>
                </div>
            {% endif %}
        </p>


        <div class="form-group d-flex justify-content-center mb-1">
            <div class="btn-group" role="group" aria-label="Размеры" id="size">
                <p class="card-text">
                    <label class="mt-2" for="size"><b>Размеры:</b></label>
                    {% for size in sizes %}
                        <button type="button" class="btn btn-outline-dark mb-1 rounded">{{ size.model_size }}</button>
                    {% endfor %}
                </p>
            </div>
         </div>

        <div class="container">
            <p class="card-text text-justify">{{ shoes.description }}</p>
        </div>

        <div id="accordion">
		  <div class="card">
		    <div class="card-header" id="headingOne">
		      <h3 class="mb-0">
		        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="color: black;">
		          <b>Как подобрать размер?</b>
		        </button>
		      </h3>
		    </div>

		    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
		      <div class="card-body">
		        <a class="btn btn-link" data-toggle="modal" data-target="#size-table-zoom">
				  	<img class="img-fluid rounded mx-auto d-block" src="{{ size_table.url }}" alt="{{ shoes.category.name }} {{ shoes.model }} size table" style="margin-top: 10px;">
				</a>

				<!-- Modal -->
				<div class="modal fade" id="size-table-zoom" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
				  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
				    <div class="modal-content">
				      <div class="modal-body">

				      	<button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      	<p style="text-align: center;" id="exampleModalLongTitle">{{ shoes.category.name }} {{ shoes.model }}</p>

				        <img class="img-fluid card-img-top rounded d-block" src="{{ size_table.url }}" alt="{{ shoes.category.name }} {{ shoes.model }}">
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
				      </div>
				    </div>
				  </div>
				</div>
				<!-- End modal -->
		      </div>
		    </div>
		  </div>


          <div class="card">
		    <div class="card-header" id="headingTwo">
		      <h4 class="mb-0">
		        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" style="color: black;">
		          <b>Условия возврата</b>
		        </button>
		      </h4>
		    </div>

		    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
		      <div class="card-body">
		        <p class="card-text">Возврат товара в течении 14 дней за счет покупателя.</p>

		        <!-- Button trigger modal -->
				<button type="button" class="btn btn-info bg-info text-white" data-toggle="modal" data-target="#exampleModalCenter" style="color: black;">
				  <span>Подробнее</span>
				</button>

				<!-- Modal -->
				<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h4 class="modal-title" id="exampleModalLongTitle">Условия возврата и обмена</h4>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-body">
				        <h4>Условия возврата и обмена</h4>
				      	<p class="modal-body">Компания осуществляет возврат и обмен этого товара в соответствии с требованиями законодательства.</p>
				      	<h4>Сроки возврата</h4>
				      	<div style="text-align: left;">
							Возврат возможен в течении 14 дней после получения (для товаров надлежащего качества).
							<br><br>
							Обратная доставка товаров осуществляется за счет покупателя.
							<br><br>
							Согласно действующему законодательству вы можете вернуть товар надлежащего качества или обменять его, если:
							<br>
							<ul>
								<li>товар не был в употреблении и не имеет следов использования потребителем: царапин, потёртостей, пятен и т. п.;</li>
								<li>товар полностью укомплектован и сохранена фабричная упаковка;</li>
								<li>сохранены все ярлыки и заводская маркировка;</li>
								<li>товар сохраняет товарный вид и свои потребительские свойства.</li>
							</ul>
						</div>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
				      </div>
				    </div>
				  </div>
				</div>
				<!-- End modal -->
		      </div>
		    </div>
		   </div>
		  </div>
		</div>

	    <div class="card-footer" style="margin: auto;">

	    	{% if shoes.discount == True %}
		    	<div class="d-flex justify-content-center" style="margin-top: 15px;">
		    		<p><span class="alert alert-danger text-dark" style="font-size: 18px; font-style: italic;"><s><b>Цена:</b> {{ shoes.price }} &#8372;</s> </span></p>
		    	</div>
		    	<div class="d-flex justify-content-center" style="margin-top: 15px;">
		    		<p><span class="alert alert-success text-dark" style="font-size: 18px; font-style: italic;"><b>Новая цена:</b> {{ shoes.price_after_discount }} &#8372;</span></p>
		    	</div>
		    {% else %}
		    	<div class="d-flex justify-content-center" style="margin-top: 15px;">
		    		<p><span class="alert alert-success text-dark" style="font-size: 18px; font-style: italic;"><b>Цена:</b> {{ shoes.price }} &#8372;</span></p>
		    	</div>
	    	{% endif %}

	    	<div class="d-flex justify-content-center" style="margin-top: 10px;">
                <a href="{% url 'userOrder:order' shoes.id %}" class="btn btn-success">Оформить</a>
	    	</div>
	    </div>

{% endblock content %}